name: dicoding sistem ML pipeline CI

on: 
  push:
    branches: ["main"]

jobs:
  development-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      # 1. Kloning kode repositori ke dalam virtual machine runner
      - name: clone repository code
        uses: actions/checkout@v4

      # 2. Inisialisasi Miniconda environment
      - name: miniconda setup
        uses: conda-incubator/setup-miniconda@v3
        with: 
          auto-activate-base: true
          python-version: "3.12.7"

      # 3. Instalasi MLflow CLI eksternal dengan versi spesifik
      - name: install mlflow cli
        shell: bash -el {0}
        run: |
          pip install mlflow==2.19.0

      # 4. Menjalankan Project MLflow (Training & Tuning)
      - name: run MLflow Project
        shell: bash -el {0}
        env: 
          MLFLOW_ALLOW_FILE_STORE: "true"
          MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/workflow-ci/mlproject/mlruns"
        run: |
          cd workflow-ci/mlproject
          
          # Membersihkan sisa data eksekusi lokal sebelumnya agar bersih
          rm -rf mlruns .mlflow mlflow.db
          
          # Eksekusi siklus MLflow run
          mlflow run . --env-manager=conda -P df_path="gender_classif_v7_preprocessed.csv"
      
      # 5. Menyimpan riwayat eksperimen (mlruns) kembali ke repositori Git utama
      - name: save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          
          git add workflow-ci/mlproject/mlruns/
          if ! git diff --cached --quiet; then
            git commit -m "save mlruns from CI run [skip ci]"
            git push origin main
          else
            echo "no new mlflow tracking changes detected. skipping commit"
          fi

      # 6. Mengunggah pelacakan metrik ke GitHub Artifacts
      - name: Upload MLflow artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-tracking-data
          path: workflow-ci/mlproject/mlruns/
